### PR TITLE
site: Add regex-based matching for left nav

### LINKED ISSUE #216: site: left nav active state broken for some multi-word titles
For google-cloud-ruby, the left nav active state mechanism activated with `matchServiceTitle` (introduced in #213) does not support multi-word service titles (e.g., 'Natural Language') when the name in the package path is different (e.g., `google/cloud/language`).

I am planning to fix this by replacing the `matchServiceTitle` with something more flexible, since I believe only google-cloud-ruby is using this mechanism.

### PR DESCRIPTION
**Pull request by quartzmo**
Replace `matchServiceTitle` in `manifest.json` with `patterns` in `toc.json`.

This change supports multi-word service titles (e.g., 'Natural Language') when the name in the package path is different (e.g., `google/cloud/language`).

The new solution replaces the `matchServiceTitle` introduced in #213 with a more flexible, regexp-based approach. I believe this is safe to do because my understanding is that only google-cloud-ruby is using the `matchServiceTitle` flag.

[closes #216]

### CODE REVIEW

**Comment by quartzmo** [comment]
A fragment from `toc.json` showing how `patterns` is used:

```js
{
      "title": "Error Reporting",
      "type": "google/cloud/errorreporting",
      "patterns": ["\/errorreporting"],
      "nav": [

        {
          "title": "Middleware",
          "type": "google/cloud/errorreporting/middleware"
        },
        {
          "title": "Railtie",
          "type": "google/cloud/errorreporting/railtie"
        },
        {
          "title": "V1Beta1",
          "type": "google/cloud/errorreporting/v1beta1",
          "patterns": ["\/errorreporting\/v1beta1"],
          "nav": [
            {
              "title": "ReportErrorsServiceApi",
              "type": "google/cloud/errorreporting/v1beta1/reporterrorsserviceapi"
            },
            {
              "title": "ErrorStatsServiceApi",
              "type": "google/cloud/errorreporting/v1beta1/errorstatsserviceapi"
            },
            {
              "title": "ErrorGroupServiceApi",
              "type": "google/cloud/errorreporting/v1beta1/errorgroupserviceapi"
            }
          ]
        }
      ]
    },
```

**Comment by quartzmo** [comment]
@callmehiphop Bump!

**Comment by quartzmo** [comment]
@callmehiphop @stephenplusplus I would like to merge this soon to fix a bug in google-cloud-ruby docs. OK if I go ahead and merge it myself?

**Comment by quartzmo** [comment]
@callmehiphop @stephenplusplus Bump!

File: site/src/app/docs/docs.controller.js [hunk 1]
```diff
@@ -42,22 +42,28 @@
...
       // `datastore/query`.
       if (manifest.matchPartialServiceId) {
         var partialServiceId = serviceId.split('/')[0];
         return !!serviceIdParam.match(partialServiceId);
 
-      // Match the downcase service title to any part of the serviceIdParam,
+      // If toc entry contains 'patterns', attempt to match any of them.
       // E.g., both nav parent `google/cloud/datastore` and nav child
-      // `google/datastore/v1` match the title `datastore`.
-      } else if (manifest.matchServiceTitle)  {
```
Comment (callmehiphop) [inline site/src/app/docs/docs.controller.js]: I'd be lying if I said I remember this even being an option - I know none of these changes will affect the node site, but is this something that php used?

/cc @dwsupplee @jdpedrie

Comment (quartzmo) [inline site/src/app/docs/docs.controller.js]: @callmehiphop In the latest [google-cloud-php/blob/gh-pages/manifest.json](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/gh-pages/manifest.json) google-cloud-php uses the older `matchPartialServiceId` option (which is where I got the "match" naming). It does not use the week-old `matchServiceTitle` that I introduced for our new use case of matching GAPIC namespaces in google-cloud-ruby.

Comment (callmehiphop) [inline site/src/app/docs/docs.controller.js]: Awesome, everything LGTM then!
